# Template for a pipeline that keeps the build-file up to date. Might come handy some day.
# name: Push to master

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build_pipeline:
#     if: "!contains(github.event.commits[0].message, '[skip ci]'"
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Setup Node
#         uses: actions/setup-node@v1
#         with:
#           node-version: "18.0.0"
#           registry-url: "https://registry.npmjs.org"
#       - name: Install dependencies
#         run: npm install
#       - name: Build
#         run: npm build
#       - name: Commit new build file and changes
#         run: |
#           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git config --local user.name "github-actions[bot]"
#           git commit -m "Up-to-date build folder" -a
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.ref }}


